remote_theme: "daviddarnes/alembic"
title: "An Ode to the Lone Scientist"
description: "For the men and women of Science, walking along paths unknown"
#logo: "walk-alone.jpg"


# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation


# 3. Gem settings
paginate: 1 # jekyll-paginate > items per page

author: RahulMadhavan # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Rahul Madhavan # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/rahul.maddy
    - https://www.linkedin.com/in/rahul-madhavan/

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "assets/walk-alone.jpg" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
#logo: "walk-alone.jpg" # Site logo, also used in jekyll-seo-tag
url: "https://p10rahulm.github.io/Ode-to-the-lone-scientist/" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/p10rahulm/Ode-to-the-lone-scientist"
email: "rahul.maddy@gmail.com"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

navigation_footer:
  Created by p10rahulm: https://github.com/p10rahulm

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/rahul-madhavan
  GitHub: https://github.com/p10rahulm

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#555"
  facebook: "#555"
  Google+: "#555"
